In [23]:
#file1 = "./TarefaAdicional/Candidato_1/Informações de Inscrição.csv"
#file2 = "./TarefaAdicional/Candidato_2/Informações de Inscrição.csv"
lista=[]
#file=[]
#pegar as varias paths dos varios arquivos e append para construir a lista das listas dos arquivos
filelist = os.listdir("./TarefaAdicional")
for file in filelist:
    pathfile= "./TarefaAdicional/" + file + "/Informações de Inscrição.csv"
    lista.append(pd.read_csv(pathfile, sep=';', decimal=','))
    #lista.append(pd.read_csv(file2, sep=';', decimal=','))


res= pd.concat(lista)
res

,nome,id_inscricao,curso,graduacao_completa,especializacao_completa,mestrado_completo,trabalhos_eventos_nacionais,trabalhos_eventos_internacionais,artigos_sem_qualis,artigos_qualis_b5_c,...,tempo_docencia,nota_cv,area,tematica_1,tematica_2,tematica_3,tematica_4,tematica_5,nota_producao_bibliografica,nota_producao_tecnica_tecnologica
0,Candidato 1,2022-02929,Doutorado,Sim,Sim,Sim,1,2,0,0,...,1,3.693548,Gestão do Conhecimento,temática 1,temática 2,temática 8,tematica 9,tematica 12,7,10
0,Candidato 2,2022-02812,Doutorado,Sim,Não,Sim,1,0,0,0,...,1,4.122232,Mídia do Conhecimento,temática 1,temática 9,temática 10,tematica 13,tematica 14,5,6
0,Candidato 3,2022-19282,Doutorado,Sim,Sim,Sim,0,0,0,1,...,1,2.930399,Engenharia do Conhecimento,temática 10,temática 11,temática 15,tematica 18,tematica 19,0,6
0,Candidato 4,2022-05828,Mestrado,Sim,Sim,Não,1,0,0,0,...,0,2.128293,Gestão do Conhecimento,temática 1,temática 3,temática 5,tematica 6,tematica 9,2,5
0,Candidato 5,2022-08626,Mestrado,Sim,Não,Não,0,1,0,0,...,0,2.655652,Mídia do Conhecimento,temática 9,temática 13,temática 14,tematica 2,tematica 10,4,0
0,Candidato 6,2022-28322,Mestrado,Sim,Sim,Não,0,2,0,0,...,0,2.893722,Engenharia do Conhecimento,temática 10,temática 11,temática 16,tematica 17,tematica 18,4,2